name: Build NextJS Analyzer

on:
  push:
    paths:
      - 'implementations/**'
    branches:
      - main
  pull_request:
    paths:
      - 'implementations/**'
    branches:
      - main

jobs:
  cpp_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev
        npm install --save node-api-headers cmake-js
        npm install --save node-addon-api

    - name: Build C++ Adpm
      run: |
        npx cmake-js build -j8 -d 'implementations/cpp'
        mkdir -p implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/
        cp implementations/cpp/build/Release/NextJS_Analyser.node implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/
    
    - name: Upload C++ Addon artifact
      uses: actions/upload-artifact@v2
      with:
        name: cpp-addon-artifact
        path: implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/NextJS_Analyser.node

    - name: C++ Tests
      run: |
        cd implementations/cpp/build
        ctest 
  
  typescript_build_and_test:
    needs: cpp_build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    # Install dependencies for the whole TypeScript project
    - name: Install dependencies root
      run: npm install
      working-directory: ./
    
    - name: Install dependencies /typescript
      run: npm install
      working-directory: ./implementations/typescript

    - name: Download C++ Addon artifact
      uses: actions/download-artifact@v2
      with:
        name: cpp-addon-artifact
        path: implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/


    # Build the main TypeScript project
    - name: Build TypeScript project
      run: npx tsc -p ./src
      working-directory: ./implementations/typescript

    - name: Test TypeScript project
      run: npm run test:ts
      working-directory: ./

  publish_package:
    needs: [typescript_build_and_test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Download C++ Addon artifact
      uses: actions/download-artifact@v2
      with:
        name: cpp-addon-artifact
        path: implementations/cpp/build/Release

    - name: Build VS Code Extension
      run: |
        npm install
        npm run compile
        npm install -g vsce
      working-directory: ./implementations/typescript/nextjs-code-analyzer-extension

    - name: Package VS Code Extension
      run: vsce package
      working-directory: ./implementations/typescript/nextjs-code-analyzer-extensions

    - name: Publish to Visual Studio Marketplace
      run: vsce publish -p ${{ secrets.VSCE_PAT }}
      working-directory: ./implementations/typescript/nextjs-code-analyzer-extensions