name: Build NextJS Analyzer

on:
  push:
    paths:
      - 'implementations/**'
    branches:
      - main
  pull_request:
    paths:
      - 'implementations/**'
    branches:
      - main

jobs:
  cpp_build_ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev
        npm install --save node-api-headers cmake-js
        npm install --save node-addon-api

    - name: Build C++ Addon
      run: |
        npx cmake-js build -j8 -d 'implementations/cpp'
        mkdir -p implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/
        cp implementations/cpp/build/Release/NextJS_Analyser.node implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/NextJS_Analyser_ubuntu.node
    
    - name: Upload C++ Addon artifact
      uses: actions/upload-artifact@v2
      with:
        name: cpp-addon-artifact-ubuntu
        path: implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/NextJS_Analyser_ubuntu.node

    - name: C++ Tests
      run: |
        cd implementations/cpp/build
        ctest 
  
  cpp_build-x86_64:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies (macOS)
      run: |
        brew install cmake
        brew install boost
        npm install
        npm install --save node-api-headers cmake-js
        npm install --save node-addon-api

    - name: Build C++ Addon (macOS)
      run: |
        npx cmake-js build -j8 -d 'implementations/cpp'
        mkdir -p implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/
        cp implementations/cpp/build/Release/NextJS_Analyser.node implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/NextJS_Analyser_macOs_x86_64.node
    
    - name: Upload C++ Addon artifact (macOS)
      uses: actions/upload-artifact@v2
      with:
        name: cpp-addon-artifact-macOs_x86_64
        path: implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/NextJS_Analyser_macOs_x86_64.node


  cpp_build_arm64:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies (macOS)
      run: |
        brew install cmake
        brew install boost
        npm install
        npm install --save node-api-headers cmake-js
        npm install --save node-addon-api

    - name: Build C++ Addon (macOS)
      run: |
        npx cmake-js build -j8 --arch=arm64 -d 'implementations/cpp'
        mkdir -p implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/
        cp implementations/cpp/build/Release/NextJS_Analyser.node implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/NextJS_Analyser_macOs_arm64.node
    
    - name: Upload C++ Addon artifact (macOS)
      uses: actions/upload-artifact@v2
      with:
        name: cpp-addon-artifact-macOs_arm64
        path: implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/NextJS_Analyser_macOs_arm64.node

  publish_package:
    needs: [cpp_build_ubuntu, cpp_build-x86_64, cpp_build_arm64]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Download C++ Addon artifact
      uses: actions/download-artifact@v2
      with:
        name: cpp-addon-artifact-macOs_x86_64
        path: implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/

    - name: Download C++ Addon artifact
      uses: actions/download-artifact@v2
      with:
        name: cpp-addon-artifact-macOs_arm64
        path: implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/

    - name: Download C++ Addon artifact
      uses: actions/download-artifact@v2
      with:
        name: cpp-addon-artifact-ubuntu
        path: implementations/typescript/nextjs-code-analyzer-extension/out/cpp_build/


    - name: Install root dependencies
      run: npm install
      working-directory: ./

    - name: Install VS Code Extension
      run: |
        npm install
        npm i --save-dev @types/jest
        npm install -g @vscode/vsce
      working-directory: ./implementations/typescript/nextjs-code-analyzer-extension

    - name: Build VS Code Extension
      run: npm run compile
      working-directory: ./implementations/typescript/nextjs-code-analyzer-extension

    - name: Test VS Code Extension
      run: npm run test
      env:
        NODE_ENV: production
      working-directory: ./implementations/typescript/nextjs-code-analyzer-extension

    - name: Package VS Code Extension
      run: vsce package
      working-directory: ./implementations/typescript/nextjs-code-analyzer-extension
      
    - name: Publish to Visual Studio Marketplace
      run: vsce publish -p ${{ secrets.VSCE_PAT }}
      working-directory: ./implementations/typescript/nextjs-code-analyzer-extension