name: Build NextJS Analyzer

on:
  push:
    paths:
      - 'implementations/**'
    branches:
      - main
  pull_request:
    paths:
      - 'implementations/**'
    branches:
      - main

jobs:
  publish_package:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Set NODE_ENV to production
      run: echo "NODE_ENV=production" >> $GITHUB_ENV

    - name: Install root dependencies
      run: npm install
      working-directory: ./
      
    - name: Build VS Code Extension
      run: |
        npm install
        npm install -g vsce
        npm run compile
      working-directory: ./implementations/typescript/nextjs-code-analyzer-extension
