name: Build NextJS Analyzer

on:
  push:
    paths:
      - 'implementations/**'
    branches:
      - main
  pull_request:
    paths:
      - 'implementations/**'
    branches:
      - main

jobs:
  typescript_build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install root dependencies
      run: npm install
      working-directory: ./

    - name: Install TypeScript project dependencies
      run: npm install
      working-directory: ./implementations/typescript/src

    - name: Build TypeScript project
      run: npm run build
      working-directory: ./implementations/typescript/src